# Stock universe seed — Sector classification sourced from Zerodha's public
# sector browser (zerodha.com/markets/sector/), top market-cap names per sector.
# This is a STARTER universe (~120 names across 5 sectors) — extend over time
# by adding more sectors using the same pattern.

UNIVERSE = [
    # ── Financial Services ──────────────────────────────────────────────
    ("HDFCBANK", "Financial Services", "Private Sector Bank"),
    ("ICICIBANK", "Financial Services", "Private Sector Bank"),
    ("SBIN", "Financial Services", "Public Sector Bank"),
    ("BAJFINANCE", "Financial Services", "NBFC"),
    ("LICI", "Financial Services", "Life Insurance"),
    ("AXISBANK", "Financial Services", "Private Sector Bank"),
    ("KOTAKBANK", "Financial Services", "Private Sector Bank"),
    ("BAJAJFINSV", "Financial Services", "Diversified Financial Services"),
    ("SHRIRAMFIN", "Financial Services", "NBFC"),
    ("SBILIFE", "Financial Services", "Life Insurance"),
    ("BSE", "Financial Services", "Exchanges & Platforms"),
    ("ICICIAMC", "Financial Services", "Asset Management"),
    ("JIOFIN", "Financial Services", "Diversified Financial Services"),
    ("PFC", "Financial Services", "PSU Infra Finance"),
    ("BANKBARODA", "Financial Services", "Public Sector Bank"),
    ("TATACAP", "Financial Services", "NBFC"),
    ("UNIONBANK", "Financial Services", "Public Sector Bank"),
    ("PNB", "Financial Services", "Public Sector Bank"),
    ("CHOLAFIN", "Financial Services", "NBFC"),
    ("CANBK", "Financial Services", "Public Sector Bank"),
    ("HDFCLIFE", "Financial Services", "Life Insurance"),
    ("MUTHOOTFIN", "Financial Services", "NBFC"),
    ("INDIANB", "Financial Services", "Public Sector Bank"),
    ("HDFCAMC", "Financial Services", "Asset Management"),
    ("RECLTD", "Financial Services", "PSU Infra Finance"),
    ("ABCAPITAL", "Financial Services", "NBFC"),
    ("ICICIGI", "Financial Services", "General Insurance"),
    ("FEDERALBNK", "Financial Services", "Private Sector Bank"),
    ("AUBANK", "Financial Services", "Small Finance Bank"),
    ("MCX", "Financial Services", "Exchanges & Platforms"),
    ("YESBANK", "Financial Services", "Private Sector Bank"),
    ("INDUSINDBK", "Financial Services", "Private Sector Bank"),
    ("LTF", "Financial Services", "NBFC"),
    ("BANKINDIA", "Financial Services", "Public Sector Bank"),
    ("MAHABANK", "Financial Services", "Public Sector Bank"),
    ("IDFCFIRSTB", "Financial Services", "Private Sector Bank"),
    ("SBICARD", "Financial Services", "NBFC"),
    ("MFSL", "Financial Services", "Life Insurance"),
    ("MOTILALOFS", "Financial Services", "Brokerage & Wealth"),
    ("SUNDARMFIN", "Financial Services", "NBFC"),
    ("HUDCO", "Financial Services", "PSU Infra Finance"),
    ("POONAWALLA", "Financial Services", "NBFC"),
    ("BANDHANBNK", "Financial Services", "Private Sector Bank"),
    ("STARHEALTH", "Financial Services", "General Insurance"),
    ("LICHSGFIN", "Financial Services", "Housing Finance"),
    ("ANGELONE", "Financial Services", "Brokerage & Wealth"),
    ("CDSL", "Financial Services", "Depositories & Clearing"),
    ("CUB", "Financial Services", "Private Sector Bank"),
    ("JMFINANCIL", "Financial Services", "Diversified Financial Services"),

    # ── IT / Internet Platforms ──────────────────────────────────────────
    ("ETERNAL", "Information Technology", "Internet & E-Commerce"),
    ("PAYTM", "Information Technology", "Fintech Platforms"),
    ("NAUKRI", "Information Technology", "Internet & E-Commerce"),
    ("IRCTC", "Information Technology", "Internet & E-Commerce"),
    ("INDIAMART", "Information Technology", "B2B Marketplaces"),
    ("JUSTDIAL", "Information Technology", "Internet & E-Commerce"),

    # ── Software Services ────────────────────────────────────────────────
    ("TCS", "Information Technology", "IT Services"),
    ("INFY", "Information Technology", "IT Services"),
    ("HCLTECH", "Information Technology", "IT Services"),
    ("WIPRO", "Information Technology", "IT Services"),
    ("TECHM", "Information Technology", "IT Services"),
    ("LTM", "Information Technology", "IT Services"),
    ("OFSS", "Information Technology", "Enterprise Platforms"),
    ("PERSISTENT", "Information Technology", "IT Services"),
    ("COFORGE", "Information Technology", "IT Services"),
    ("MPHASIS", "Information Technology", "IT Services"),
    ("LTTS", "Information Technology", "ER&D / Product Software"),
    ("HEXT", "Information Technology", "IT Services"),
    ("TATATECH", "Information Technology", "ER&D / Product Software"),
    ("TATAELXSI", "Information Technology", "ER&D / Product Software"),
    ("KPITTECH", "Information Technology", "ER&D / Product Software"),
    ("AFFLE", "Information Technology", "Analytics & Data Services"),
    ("FSL", "Information Technology", "BPO/ITeS"),
    ("ZENSARTECH", "Information Technology", "IT Services"),
    ("NAZARA", "Information Technology", "Digital Entertainment"),
    ("SYRMA", "Information Technology", "Electronic Manufacturing Services"),

    # ── Healthcare / Pharma ───────────────────────────────────────────────
    ("SUNPHARMA", "Healthcare", "Pharma - Formulators"),
    ("DIVISLAB", "Healthcare", "Pharma - API & CRAMS"),
    ("TORNTPHARM", "Healthcare", "Pharma - Formulators"),
    ("APOLLOHOSP", "Healthcare", "Hospitals"),
    ("DRREDDY", "Healthcare", "Pharma - Formulators"),
    ("LUPIN", "Healthcare", "Pharma - Formulators"),
    ("CIPLA", "Healthcare", "Pharma - Formulators"),
    ("MAXHEALTH", "Healthcare", "Hospitals"),
    ("ZYDUSLIFE", "Healthcare", "Pharma - Formulators"),
    ("MANKIND", "Healthcare", "Pharma - Formulators"),
    ("AUROPHARMA", "Healthcare", "Pharma - Formulators"),
    ("FORTIS", "Healthcare", "Hospitals"),
    ("GLENMARK", "Healthcare", "Pharma - Formulators"),
    ("ALKEM", "Healthcare", "Pharma - Formulators"),
    ("LAURUSLABS", "Healthcare", "Pharma - API & CRAMS"),
    ("BIOCON", "Healthcare", "Pharma - API & CRAMS"),
    ("ABBOTINDIA", "Healthcare", "Pharma - Formulators"),
    ("IPCALAB", "Healthcare", "Pharma - Formulators"),
    ("GRANULES", "Healthcare", "Pharma - API/Formulators"),
    ("BLISSGVS", "Healthcare", "Pharma - Formulators"),
    ("ACUTAAS", "Healthcare", "Specialty Chemicals - Pharma"),
    ("SUVEN", "Healthcare", "Pharma - Formulators"),
    ("MEDPLUS", "Healthcare", "Pharmacy Retail"),
    ("NH", "Healthcare", "Hospitals"),

    # ── Metals & Mining ───────────────────────────────────────────────────
    ("COALINDIA", "Materials", "Coal & Mining"),
    ("JSWSTEEL", "Materials", "Iron & Steel Core"),
    ("VEDL", "Materials", "Diversified Metals"),
    ("TATASTEEL", "Materials", "Iron & Steel Core"),
    ("HINDZINC", "Materials", "Copper & Specialty Metallurgy"),
    ("HINDALCO", "Materials", "Aluminium & Base Metals"),
    ("JINDALSTEL", "Materials", "Iron & Steel Core"),
    ("NMDC", "Materials", "Iron Ore & Mineral Mining"),
    ("NATIONALUM", "Materials", "Aluminium & Base Metals"),
    ("SAIL", "Materials", "Iron & Steel Core"),
    ("JSL", "Materials", "Iron & Steel Products"),
    ("HINDCOPPER", "Materials", "Copper & Specialty Metallurgy"),
    ("HSCL", "Materials", "Carbon Black"),
    ("MANINDS", "Materials", "Steel Tubes & Pipes"),

    # ── Industrials / Defense / Aerospace ────────────────────────────────
    ("BEL", "Industrials", "Aerospace & Defense OEM"),
    ("AEROFLEX", "Industrials", "Industrial Products"),
    ("BELRISE", "Industrials", "Chassis & Metal Parts"),
    ("FINCABLES", "Industrials", "Cables & Wires"),
    ("GARUDA", "Industrials", "Construction & Engineering"),
    ("JNKINDIA", "Industrials", "Industrial Products"),

    # ── Utilities / Energy ────────────────────────────────────────────────
    ("ADANIPOWER", "Utilities", "Integrated Utilities"),
    ("OIL", "Energy", "Oil & Gas E&P"),
    ("KPEL", "Utilities", "Renewable Energy"),
    ("KPIGREEN", "Utilities", "Renewable Energy"),

    # ── Consumer Discretionary ───────────────────────────────────────────
    ("M&M", "Consumer Discretionary", "Passenger Cars"),
    ("LENSKART", "Consumer Discretionary", "Apparel Retail Chains"),
    ("EVEREADY", "Consumer Discretionary", "Batteries & Lighting"),

    # ── Energy expansion (Jun 2026) — was only OIL, now broad coverage ──
    ("RELIANCE", "Energy", "Diversified Energy"),
    ("NTPC", "Energy", "Power Generation"),
    ("ONGC", "Energy", "Oil & Gas E&P"),
    ("POWERGRID", "Energy", "Power Transmission"),
    ("ADANIGREEN", "Energy", "Renewable Energy"),
    ("IOC", "Energy", "Oil Refiners"),
    ("ADANIENSOL", "Energy", "Power Transmission"),
    ("BPCL", "Energy", "Oil Refiners"),
    ("TATAPOWER", "Energy", "Integrated Utilities"),
    ("GAIL", "Energy", "Gas Utilities"),
    ("JSWENERGY", "Energy", "Power Generation"),
    ("HINDPETRO", "Energy", "Oil Refiners"),
    ("ATGL", "Energy", "Gas Utilities"),
    ("NHPC", "Energy", "Power Generation"),
    ("TORNTPOWER", "Energy", "Integrated Utilities"),
    ("LINDEINDIA", "Energy", "Industrial Gases"),
    ("GUJGASLTD", "Energy", "Gas Utilities"),
    ("NLCINDIA", "Energy", "Coal & Mining"),
    ("PETRONET", "Energy", "Gas Utilities"),
    ("SJVN", "Energy", "Power Generation"),
    ("MRPL", "Energy", "Oil Refiners"),
    ("IGL", "Energy", "Gas Utilities"),
    ("CESC", "Energy", "Integrated Utilities"),

    # ── Consumer Discretionary expansion (Jun 2026) — was 3, now broader ──
    ("LGEINDIA", "Consumer Discretionary", "Household White Goods"),
    ("VOLTAS", "Consumer Discretionary", "HVAC & Cooling"),
    ("BLUESTARCO", "Consumer Discretionary", "HVAC & Cooling"),
    ("HONAUT", "Consumer Discretionary", "Industrial Automation"),
    ("CPPLUS", "Consumer Discretionary", "Consumer Electronics"),
    ("CROMPTON", "Consumer Discretionary", "Household White Goods"),
    ("VGUARD", "Consumer Discretionary", "Household White Goods"),
    ("WHIRLPOOL", "Consumer Discretionary", "Household White Goods"),
    ("TTKPRESTIG", "Consumer Discretionary", "Houseware & Glass"),
    ("SYMPHONY", "Consumer Discretionary", "HVAC & Cooling"),
    ("IFBIND", "Consumer Discretionary", "Household White Goods"),
    ("BAJAJELEC", "Consumer Discretionary", "Household White Goods"),
    ("HAWKINCOOK", "Consumer Discretionary", "Houseware & Glass"),
    ("ORIENTELEC", "Consumer Discretionary", "Household White Goods"),
    ("BOSCH-HCIL", "Consumer Discretionary", "HVAC & Cooling"),
    ("BOROSIL", "Consumer Discretionary", "Houseware & Glass"),
]

print(f"Universe seeded: {len(UNIVERSE)} tickers")
