[theme]
base = "light"
primaryColor = "#10B981"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#334155"
font = "sans serif"

[server]
headless = false
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false
